version: 2

sources:
  - name: jaffle_shop
    tables:
      - name: raw_customers
        meta:
          dagster:
            asset_key: ["raw_customers"] # This metadata specifies the corresponding Dagster asset for this dbt source.
